name: Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: ['*']

jobs:
  build:

    strategy:
      matrix:
        node-version: [17]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      # - name: Check coding standards
      #   if: matrix.node-version == '16.x' && matrix.os == 'ubuntu-latest'
      #   run: npm run lint
      - name: Static analysis - check types
        run: npm run ts
      - name: Text with coverage
        run: npm run coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: coverage/lcov.info
          env_vars: OS,NODE
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
